run:
  timeout: 5m
  tests: true

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 120
  goimports:
    local-prefixes: axon
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - misspell
    - goconst
    - gocyclo
    - dupl
    - lll
    - unparam
    - unconvert
    - gocritic
  disable:
    - gosec  # Security linter - too strict for this project
    - exhaustive # Exhaustive switch statements - not needed
    - gochecknoinits # Allow init functions
    - gochecknoglobals # Allow global variables for configs

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    # Exclude main.go from some checks
    - path: main\.go
      linters:
        - gochecknoglobals
  max-same-issues: 0
  max-issues-per-linter: 0

severity:
  default-severity: error

